apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xx4rv8bwn-go-gitops
  description: This is GitOps manifest for xx4rv8bwn-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xx4rv8bwn-go
    backstage.io/kubernetes-id: xx4rv8bwn-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xx4rv8bwn-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xx4rv8bwn-go
